### ISSUE TITLE
Icons not showing

### ISSUE THREAD

**Issue by keigol** [jonseppanen/Raindock#8]
Dock works perfect except the icons are not showing

**Comment by jonseppanen** [comment]
Is imagemagick installed as per magickmeter instructions? Do the magickmeter example skins work?

**Comment by keigol** [comment]
Only SexyClock and UnderClock work

Thanks

**Comment by jonseppanen** [comment]
What version/type of imagemagick did you install?

**Comment by keigol** [comment]
ImageMagick-7.0.7-21-Q16-x64-dll.exe
from Windows Binary Release

**Comment by jonseppanen** [comment]
Is there any errors in your rainmeter log? Which OS are you using?

**Comment by keigol** [comment]
Windows 10
it says
"MaskImageName: Unable to open: C:\Users\abc\AppData\Local\Temp\Raindock\mask.bmp (Raindock\raindock.ini)"
and
"ImageName: Unable to open: C:\Users\abc\AppData\Local\Temp\raindock\firefox.bmp (Raindock\raindock.ini)"

**Comment by jonseppanen** [comment]
Can you tell me if this dir:

C:\Users\abc\AppData\Local\Temp\raindock

Exists on your machine?

**Comment by keigol** [comment]
Yes it does

**Comment by keigol** [comment]
Im not sure if they are supposed to be but the icons are not in that folder.
They are in the raindock @resources folder though

**Comment by jonseppanen** [comment]
The icons are in the right place. They should be converted to BMP files and placed in the Temp dir. Magickmeter is used to do this.

Is there *any* bmp files in the Temp dir?

**Comment by keigol** [comment]
Nope they are all .ico

**Comment by jonseppanen** [comment]
Something is not working with your magickmeter plugin. Can you try reboot your PC and see if that activates it?

**Comment by keigol** [comment]
I already have restarted my pc twice should i reinstall it maybe?

**Comment by keigol** [comment]
its working! I had to check a box that says "Install legacy utilites (e.g. convert)" when installing. Thank you so much I really appreciate your help!!

**Comment by jonseppanen** [comment]
Good to hear!
